// <auto-generated />
using System;
using FinancieraSoluciones.Infraestructura.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infraestructura.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Cobranza.Liquidaciones.LiquidacionCobranza", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CobradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("cobrador_id");

                    b.Property<Guid?>("ConfirmadaPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmada_por_id");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estatus");

                    b.Property<string>("Evidencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("evidencia");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<DateTime?>("FechaConfirmacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_confirmacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Hora")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("hora");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.Property<decimal>("TotalEfectivo")
                        .HasColumnType("numeric")
                        .HasColumnName("total_efectivo");

                    b.Property<decimal>("TotalTransferencia")
                        .HasColumnType("numeric")
                        .HasColumnName("total_transferencia");

                    b.HasKey("Id");

                    b.HasIndex("Estatus");

                    b.HasIndex("CobradorId", "Fecha");

                    b.ToTable("liquidaciones_cobranza", (string)null);
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Finanzas.Caja.CierreDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CerradoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("cerrado_por_id");

                    b.Property<string>("Evidencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("evidencia");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cierre");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .IsUnique();

                    b.ToTable("cierres_diarios", (string)null);
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Finanzas.Caja.MovimientoCaja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Abono")
                        .HasColumnType("numeric")
                        .HasColumnName("abono");

                    b.Property<Guid?>("CobradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("cobrador_id");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("concepto");

                    b.Property<Guid?>("CorteCajaId")
                        .HasColumnType("uuid")
                        .HasColumnName("corte_caja_id");

                    b.Property<Guid?>("CreditoId")
                        .HasColumnType("uuid")
                        .HasColumnName("credito_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Hora")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("hora");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("LiquidacionCobranzaId")
                        .HasColumnType("uuid")
                        .HasColumnName("liquidacion_cobranza_id");

                    b.Property<string>("Medio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("medio");

                    b.Property<decimal?>("MontoEfectivo")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_efectivo");

                    b.Property<decimal?>("MontoTransferencia")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_transferencia");

                    b.Property<decimal?>("Mora")
                        .HasColumnType("numeric")
                        .HasColumnName("mora");

                    b.Property<int?>("NumeroFicha")
                        .HasColumnType("integer")
                        .HasColumnName("numero_ficha");

                    b.Property<bool>("RegistraCaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("registra_caja");

                    b.Property<Guid?>("ReversaDeId")
                        .HasColumnType("uuid")
                        .HasColumnName("reversa_de_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("CobradorId");

                    b.HasIndex("CreditoId");

                    b.HasIndex("Fecha");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("LiquidacionCobranzaId");

                    b.HasIndex("ReversaDeId");

                    b.HasIndex("CorteCajaId", "Fecha");

                    b.HasIndex("CreditoId", "NumeroFicha");

                    b.ToTable("movimientos_caja", (string)null);
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Finanzas.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("apellido");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Negocio")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("negocio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("zona");

                    b.HasKey("Id");

                    b.HasIndex("Activo", "Estatus");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Finanzas.Cortes.CorteCaja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Diferencia")
                        .HasColumnType("numeric")
                        .HasColumnName("diferencia");

                    b.Property<string>("Evidencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("evidencia");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("folio");

                    b.Property<string>("Hora")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("hora");

                    b.Property<Guid>("RealizadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("realizado_por_id");

                    b.Property<decimal>("TotalReal")
                        .HasColumnType("numeric")
                        .HasColumnName("total_real");

                    b.Property<decimal>("TotalTeorico")
                        .HasColumnType("numeric")
                        .HasColumnName("total_teorico");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("Folio")
                        .IsUnique();

                    b.ToTable("cortes_caja", (string)null);
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Finanzas.Credito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AplicarFeriados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("aplicar_feriados");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<decimal>("Cuota")
                        .HasColumnType("numeric")
                        .HasColumnName("cuota");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("folio");

                    b.Property<decimal>("InteresTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("interes_total");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric")
                        .HasColumnName("monto");

                    b.Property<decimal>("Pagado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("pagado");

                    b.Property<bool>("PermitirDomingo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("permitir_domingo");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.Property<int>("TotalFichas")
                        .HasColumnType("integer")
                        .HasColumnName("total_fichas");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Estatus");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("Folio")
                        .IsUnique();

                    b.HasIndex("Estatus", "Tipo");

                    b.ToTable("creditos", (string)null);
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Finanzas.Ficha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Abono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("abono");

                    b.Property<decimal>("Capital")
                        .HasColumnType("numeric")
                        .HasColumnName("capital");

                    b.Property<bool>("Cerrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cerrada");

                    b.Property<Guid>("CreditoId")
                        .HasColumnType("uuid")
                        .HasColumnName("credito_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("folio");

                    b.Property<string>("Hora")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("hora");

                    b.Property<decimal>("Interes")
                        .HasColumnType("numeric")
                        .HasColumnName("interes");

                    b.Property<decimal>("Mora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("mora");

                    b.Property<decimal>("MoraAcumulada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("mora_acumulada");

                    b.Property<int>("Num")
                        .HasColumnType("integer")
                        .HasColumnName("num");

                    b.Property<bool>("Pagada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pagada");

                    b.Property<decimal>("SaldoCap")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_cap");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("CreditoId", "Num")
                        .IsUnique();

                    b.HasIndex("CreditoId", "Pagada");

                    b.HasIndex("Pagada", "Fecha");

                    b.ToTable("fichas", (string)null);
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.General.AuditoriaEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("accion");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("detalle");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<string>("EntidadTipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("entidad_tipo");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EntidadTipo", "EntidadId");

                    b.ToTable("auditoria_eventos", (string)null);
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.General.ConfiguracionSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AplicarFeriadosDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("aplicar_feriados_default");

                    b.Property<int>("DiasGraciaDiaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("dias_gracia_diaria");

                    b.Property<int>("DiasGraciaSemanal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("dias_gracia_semanal");

                    b.Property<bool>("DomingoInhabilDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("domingo_inhabil_default");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<int>("LockoutMaxFailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("lockout_max_failed_attempts");

                    b.Property<int>("LockoutMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15)
                        .HasColumnName("lockout_minutes");

                    b.Property<decimal>("MoraDiaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(20m)
                        .HasColumnName("mora_diaria");

                    b.Property<decimal>("MoraSemanal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(150m)
                        .HasColumnName("mora_semanal");

                    b.Property<int>("PasswordExpireDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(90)
                        .HasColumnName("password_expire_days");

                    b.Property<int>("PasswordHistoryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("password_history_count");

                    b.Property<int>("PasswordMinLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(8)
                        .HasColumnName("password_min_length");

                    b.Property<bool>("PasswordRequireDigit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("password_require_digit");

                    b.Property<bool>("PasswordRequireLower")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("password_require_lower");

                    b.Property<bool>("PasswordRequireSpecial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("password_require_special");

                    b.Property<bool>("PasswordRequireUpper")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("password_require_upper");

                    b.Property<decimal>("TasaDiaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0.15m)
                        .HasColumnName("tasa_diaria");

                    b.Property<decimal>("TasaSemanal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0.2m)
                        .HasColumnName("tasa_semanal");

                    b.Property<decimal>("TopeMoraDiaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("tope_mora_diaria");

                    b.Property<decimal>("TopeMoraSemanal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("tope_mora_semanal");

                    b.HasKey("Id");

                    b.ToTable("configuracion_sistema", (string)null);
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.General.Feriado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Fecha")
                        .IsUnique();

                    b.ToTable("feriados", (string)null);
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.General.ZonaCobranza", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Orden");

                    b.ToTable("zonas_cobranza", (string)null);
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Seguridad.Boton", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("clave");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid>("IdPagina")
                        .HasColumnType("uuid")
                        .HasColumnName("id_pagina");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.HasIndex("IdPagina", "Orden");

                    b.ToTable("botones", (string)null);
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Seguridad.Modulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("clave");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icono");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.HasIndex("Orden");

                    b.ToTable("modulos", (string)null);
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Seguridad.Pagina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("clave");

                    b.Property<bool>("EnMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("en_menu");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid>("IdModulo")
                        .HasColumnType("uuid")
                        .HasColumnName("id_modulo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ruta");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.HasIndex("IdModulo", "Orden");

                    b.ToTable("paginas", (string)null);
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Seguridad.PasswordHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UsuarioId");

                    b.ToTable("password_history", (string)null);
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Seguridad.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UsedAt");

                    b.HasIndex("UsuarioId", "Codigo")
                        .IsUnique();

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Seguridad.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("clave");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.HasIndex("Orden");

                    b.ToTable("perfiles", (string)null);
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Seguridad.PermisoBoton", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asignacion");

                    b.Property<Guid>("IdBoton")
                        .HasColumnType("uuid")
                        .HasColumnName("id_boton");

                    b.Property<Guid>("IdPerfil")
                        .HasColumnType("uuid")
                        .HasColumnName("id_perfil");

                    b.Property<bool>("TienePermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("tiene_permiso");

                    b.HasKey("Id");

                    b.HasIndex("IdBoton");

                    b.HasIndex("IdPerfil", "IdBoton")
                        .IsUnique();

                    b.ToTable("permisos_boton", (string)null);
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Seguridad.PermisoModulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asignacion");

                    b.Property<Guid>("IdModulo")
                        .HasColumnType("uuid")
                        .HasColumnName("id_modulo");

                    b.Property<Guid>("IdPerfil")
                        .HasColumnType("uuid")
                        .HasColumnName("id_perfil");

                    b.Property<bool>("TienePermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("tiene_permiso");

                    b.HasKey("Id");

                    b.HasIndex("IdModulo");

                    b.HasIndex("IdPerfil", "IdModulo")
                        .IsUnique();

                    b.ToTable("permisos_modulo", (string)null);
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Seguridad.PermisoPagina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asignacion");

                    b.Property<Guid>("IdPagina")
                        .HasColumnType("uuid")
                        .HasColumnName("id_pagina");

                    b.Property<Guid>("IdPerfil")
                        .HasColumnType("uuid")
                        .HasColumnName("id_perfil");

                    b.Property<bool>("TienePermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("tiene_permiso");

                    b.HasKey("Id");

                    b.HasIndex("IdPagina");

                    b.HasIndex("IdPerfil", "IdPagina")
                        .IsUnique();

                    b.ToTable("permisos_pagina", (string)null);
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Seguridad.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_paterno");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contrasena");

                    b.Property<int>("FailedLoginCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_count");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid>("IdPerfil")
                        .HasColumnType("uuid")
                        .HasColumnName("id_perfil");

                    b.Property<Guid?>("IdZonaCobranza")
                        .HasColumnType("uuid")
                        .HasColumnName("id_zona_cobranza");

                    b.Property<DateTime?>("LockoutUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_until");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("must_change_password");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<DateTime?>("PasswordExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_expires_at");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso");

                    b.Property<string>("UsuarioAcceso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_acceso");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("IdPerfil");

                    b.HasIndex("IdZonaCobranza");

                    b.HasIndex("UsuarioAcceso")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Finanzas.Caja.MovimientoCaja", b =>
                {
                    b.HasOne("FinancieraSoluciones.Domain.Entidades.Finanzas.Cortes.CorteCaja", "CorteCaja")
                        .WithMany("Movimientos")
                        .HasForeignKey("CorteCajaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CorteCaja");
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Finanzas.Credito", b =>
                {
                    b.HasOne("FinancieraSoluciones.Domain.Entidades.Finanzas.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Finanzas.Ficha", b =>
                {
                    b.HasOne("FinancieraSoluciones.Domain.Entidades.Finanzas.Credito", "Credito")
                        .WithMany("Fichas")
                        .HasForeignKey("CreditoId")
                        .IsRequired();

                    b.Navigation("Credito");
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Seguridad.Boton", b =>
                {
                    b.HasOne("FinancieraSoluciones.Domain.Entidades.Seguridad.Pagina", "Pagina")
                        .WithMany()
                        .HasForeignKey("IdPagina")
                        .IsRequired();

                    b.Navigation("Pagina");
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Seguridad.Pagina", b =>
                {
                    b.HasOne("FinancieraSoluciones.Domain.Entidades.Seguridad.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("IdModulo")
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Seguridad.PermisoBoton", b =>
                {
                    b.HasOne("FinancieraSoluciones.Domain.Entidades.Seguridad.Boton", "Boton")
                        .WithMany()
                        .HasForeignKey("IdBoton")
                        .IsRequired();

                    b.HasOne("FinancieraSoluciones.Domain.Entidades.Seguridad.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("IdPerfil")
                        .IsRequired();

                    b.Navigation("Boton");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Seguridad.PermisoModulo", b =>
                {
                    b.HasOne("FinancieraSoluciones.Domain.Entidades.Seguridad.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("IdModulo")
                        .IsRequired();

                    b.HasOne("FinancieraSoluciones.Domain.Entidades.Seguridad.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("IdPerfil")
                        .IsRequired();

                    b.Navigation("Modulo");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Seguridad.PermisoPagina", b =>
                {
                    b.HasOne("FinancieraSoluciones.Domain.Entidades.Seguridad.Pagina", "Pagina")
                        .WithMany()
                        .HasForeignKey("IdPagina")
                        .IsRequired();

                    b.HasOne("FinancieraSoluciones.Domain.Entidades.Seguridad.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("IdPerfil")
                        .IsRequired();

                    b.Navigation("Pagina");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Seguridad.Usuario", b =>
                {
                    b.HasOne("FinancieraSoluciones.Domain.Entidades.Seguridad.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("IdPerfil")
                        .IsRequired();

                    b.HasOne("FinancieraSoluciones.Domain.Entidades.General.ZonaCobranza", "ZonaCobranza")
                        .WithMany()
                        .HasForeignKey("IdZonaCobranza")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Perfil");

                    b.Navigation("ZonaCobranza");
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Finanzas.Cortes.CorteCaja", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("FinancieraSoluciones.Domain.Entidades.Finanzas.Credito", b =>
                {
                    b.Navigation("Fichas");
                });
#pragma warning restore 612, 618
        }
    }
}
